#### Create User

POST http://localhost:3003/users/create
Content-Type: application/json

{
    "name": "Manoel",
    "email": "manoeld@.com",
    "password": "123456"
}

### Criar Post

POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "Londres",
    "description": "Turistando",
    "type": "event",
    "authorId": "adc0970e-8d70-4362-a116-2d011979f814"
}

### Post by Id

GET http://localhost:3003/post/getbyid/ac5cb17d-ec6a-4293-b2bb-2bbb8d1f9ef8

### Get All Users

GET http://localhost:3003/users/users

### Get All FriendsShip

GET http://localhost:3003/friendship/friendship


### CRiar amizade

POST http://localhost:3003/friendship/create
Content-Type: application/json

{
    "user1": "ebb44960-5c16-4977-bdcc-7e281b59c395",
    "user2": "2d23b813-94ea-445b-a156-64ef11849206"
}

### deletar

DELETE http://localhost:3003/friendship/friendship/bd636e0c-b475-4990-988f-16d95cc0bd1d
Content-Type: application/json

{
    "user2": "adc0970e-8d70-4362-a116-2d011979f814"
}


### Feed
GET http://localhost:3003/post/feed/adc0970e-8d70-4362-a116-2d011979f814

